version: '3.8'

services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tshirtprinting_app
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./uploads:/var/www/html/uploads
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: zeroweb1_namo
      DB_USERNAME: zeroweb1_namo
      DB_PASSWORD: namopass
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MariaDB Database
  db:
    image: mariadb:10.6
    container_name: tshirtprinting_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: zeroweb1_namo
      MYSQL_USER: zeroweb1_namo
      MYSQL_PASSWORD: namopass
      MARIADB_CHARACTER_SET_SERVER: utf8mb4
      MARIADB_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: tshirtprinting_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      UPLOAD_LIMIT: 300M
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data:
    driver: local 